# Generated by Django 4.0.1 on 2022-07-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
