# Generated by Django 4.0.1 on 2022-07-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_usuarios_apellido_alter_usuarios_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
